<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DarkwoodMultiplayerFramework</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\Darkwood_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony"><HintPath>..\..\Payload\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mirror">
      <HintPath>..\..\Payload\BepInEx\plugins\Mirror.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="Telepathy">
      <HintPath>..\..\Payload\BepInEx\plugins\Telepathy.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="BepInEx"><HintPath>..\..\Payload\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.AudioModule.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private>
    </Reference>
    <Reference Include="DarkwoodMultiplayerRenderSupport">
      <HintPath>..\..\Payload\BepInEx\plugins\DarkwoodMultiplayerRenderSupport.dll</HintPath><Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
