<Project>
  <PropertyGroup>
    <LocalBuildRoot>F:\Private Blog\DMF Local Build</LocalBuildRoot>
    <BaseIntermediateOutputPath>$(LocalBuildRoot)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(LocalBuildRoot)\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;src-staging\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
