<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DarkwoodMultiplayerFramework.DarkwoodAdapter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Core\DarkwoodMultiplayerFramework.Core.csproj" />
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Entities\DarkwoodMultiplayerFramework.Entities.csproj" />
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Protocol\DarkwoodMultiplayerFramework.Protocol.csproj" />
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Network\DarkwoodMultiplayerFramework.Network.csproj" />
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Actions\DarkwoodMultiplayerFramework.Actions.csproj" />
    <ProjectReference Include="..\DarkwoodMultiplayerFramework.Snapshots\DarkwoodMultiplayerFramework.Snapshots.csproj" />
    <Reference Include="Assembly-CSharp"><HintPath>..\..\..\Darkwood_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="com.rlabrecque.steamworks.net"><HintPath>..\..\..\Darkwood_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>..\..\libs\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>..\..\libs\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>..\..\..\Darkwood_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>..\..\..\Darkwood_Data\Managed\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
