using System;
using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;

namespace DarkwoodMultiplayerFramework.DarkwoodAdapter;

/// <summary>Scales only loot newly generated by the authoritative host.</summary>
[HarmonyPatch(typeof(InventoryRandom), "spawnItems")]
internal static class DarkwoodLootScalingPatch
{
    private sealed class State
    {
        public Inventory? Inventory;
        public HashSet<InvItemClass> Existing = new HashSet<InvItemClass>();
        public int Players;
    }

    private static readonly FieldInfo? InventoryField = AccessTools.Field(typeof(InventoryRandom), "inventory");

    private static void Prefix(InventoryRandom __instance, out State? __state)
    {
        __state = null;
        var runtime = DarkwoodAdapterRuntime.Instance;
        if (runtime == null || !runtime.IsHost || runtime.ConfiguredPlayerCount <= 1 || InventoryField == null) return;
        var inventory = InventoryField.GetValue(__instance) as Inventory;
        if (inventory?.slots == null) return;
        var state = new State { Inventory = inventory, Players = runtime.ConfiguredPlayerCount };
        foreach (var slot in inventory.slots) if (slot?.invItem != null) state.Existing.Add(slot.invItem);
        __state = state;
    }

    private static void Postfix(State? __state)
    {
        if (__state?.Inventory?.slots == null) return;
        foreach (var slot in __state.Inventory.slots.ToArray())
        {
            var item = slot?.invItem;
            if (item == null || __state.Existing.Contains(item)) continue;
            Scale(__state.Inventory, item, __state.Players);
        }
        __state.Inventory.refreshItems();
        DarkwoodAdapterRuntime.Instance?.NotifyHostContainerChanged(__state.Inventory);
    }

    private static void Scale(Inventory inventory, InvItemClass item, int players)
    {
        if (item.baseClass == null || players <= 1) return;
        var original = Math.Max(1, item.amount);
        if (!item.baseClass.stackable)
        {
            for (var i = 1; i < players; i++) Copy(inventory, item, original);
            return;
        }
        var total = (int)Math.Min(int.MaxValue, (long)original * players);
        var stackLimit = item.baseClass.maxAmount > 0 ? item.baseClass.maxAmount : total;
        item.amount = Math.Min(total, stackLimit);
        item.refresh();
        for (var remaining = total - item.amount; remaining > 0;)
        {
            var amount = Math.Min(remaining, stackLimit);
            // FIX-008：无空槽时停止复制——绝不把剩余量堆回原槽（会超 maxAmount 写入存档，
            // 游戏读档时校验失败导致"存档损坏/无法进入"）。
            if (!Copy(inventory, item, amount)) break;
            remaining -= amount;
        }
    }

    internal static void ScaleExistingInventory(Inventory inventory, int players)
    {
        if (inventory?.slots == null || players <= 1) return;
        var originals = new List<InvItemClass>();
        foreach (var slot in inventory.slots) if (slot?.invItem != null) originals.Add(slot.invItem);
        foreach (var item in originals) Scale(inventory, item, players);
        inventory.refreshItems();
    }

    private static bool Copy(Inventory inventory, InvItemClass source, int amount)
    {
        var slot = inventory.getNextFreeSlot();
        if (slot == null) return false;
        slot.createItem(source, amount);
        return true;
    }
}
