#!/usr/bin/env python3
"""
DMF Build Identity generator.

Reads:
  - canonical source root (SRC_ROOT, defaults to parent of script's repo companion)
  - git companion root (GH_ROOT, defaults to <SRC_ROOT>-GitHub)
Writes:
  - src/DarkwoodMultiplayerFramework.Core/BuildIdentity.cs
    (auto-generated; consumed by both Host and Client at startup)

The values baked into the assembly:
  Version             : hard-coded "0.8.9.2" in this script (override via DMF_VERSION env)
  GitCommit           : git -C GH_ROOT rev-parse HEAD  (no fake SHAs)
  GitDirty            : True if any tracked file under src/ (excluding bin/obj/build cache) differs from HEAD
  SourceFingerprint   : SHA256 over canonical src/**/*.cs sorted by path  → first 16 hex (upper-case)
  ProtocolVersion     : public const string Framework in ReplicationProtocol.cs
  BuildUtc            : ISO 8601 UTC timestamp at generation time

This script is the single source of truth — no values are typed by hand into the C# file.
"""
import subprocess, hashlib, os, datetime, re, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Repo layout: SCRIPT_DIR = .../src/tools  → SRC_ROOT = .../src  → REPO_ROOT = ...
SRC_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

def _has_git_dir(p):
    return os.path.isdir(os.path.join(p, ".git"))

# Git home resolution:
#   1) DMF_GIT_ROOT env var wins.
#   2) If REPO_ROOT itself is a git work tree (a clean clone of the public
#      repo), the identity reflects that clone's own HEAD.
#   3) Otherwise fall back to the local companion mirror "<repo>-GitHub"
#      (canonical private tree layout: the source root itself is not under git).
if os.environ.get("DMF_GIT_ROOT"):
    GH_ROOT = os.environ["DMF_GIT_ROOT"]
elif _has_git_dir(REPO_ROOT):
    GH_ROOT = REPO_ROOT
else:
    GH_ROOT = REPO_ROOT + "-GitHub"
OUT_PATH = os.path.join(SRC_ROOT, "DarkwoodMultiplayerFramework.Core", "BuildIdentity.cs")

def git(*args, cwd=GH_ROOT):
    return subprocess.run(["git", "-C", cwd] + list(args), capture_output=True, text=True).stdout.strip()

commit = git("rev-parse", "HEAD")
if not commit:
    sys.stderr.write(f"[dmf-build-identity] ERROR: cannot read git HEAD from {GH_ROOT}\n")
    sys.exit(1)

# Dirty: any tracked modification under src/ (excluding build cache / IDE junk)
status_lines = git("status", "--porcelain").splitlines()
skip_re = re.compile(r"/(bin|obj)/|\.(pdb|deps\.json|AssemblyReference\.cache|user|suo)$")
dirty = False
for L in status_lines:
    if not L or L.startswith("??"):
        continue
    idx = 3 if len(L) > 3 and L[2] == ' ' else 2
    path = L[idx:].strip()
    if not path.startswith("src/"):
        continue
    if skip_re.search("/" + path):
        continue
    if path.endswith((".cs", ".csproj", ".props", ".targets", ".config", ".json")):
        dirty = True
        break

# Source fingerprint — canonical src/**/*.cs (excludes bin/obj)
file_hashes = []
for root, dirs, files in os.walk(os.path.join(REPO_ROOT, "src")):
    dirs[:] = [d for d in dirs if d not in ("bin", "obj", ".vs")]
    for f in files:
        if not f.endswith(".cs"):
            continue
        p = os.path.join(root, f)
        rel = os.path.relpath(p, REPO_ROOT).replace("\\", "/")
        h = hashlib.sha256(open(p, "rb").read()).hexdigest()
        file_hashes.append((rel, h))
file_hashes.sort()
concat = "\n".join(f"{p} {h}" for p, h in file_hashes).encode()
src_fp = hashlib.sha256(concat).hexdigest()[:16].upper()
utc = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

# Protocol version from ReplicationProtocol.cs
proto_path = os.path.join(REPO_ROOT, "src", "DarkwoodMultiplayerFramework.Protocol", "Common", "ReplicationProtocol.cs")
text = open(proto_path, encoding="utf-8").read()
m = re.search(r'public const string Framework = "([^"]+)"', text)
proto = m.group(1) if m else "0.0.0"

version = os.environ.get("DMF_VERSION", "0.8.9.3-pre.1")

content = f"""// <auto-generated by dmf-build-identity generator>
//   commit  : git rev-parse HEAD on -GitHub companion
//   dirty   : tracked modifications under src/ (excluding bin/obj/.vs/build cache)
//   src fp  : SHA256 over canonical src/**/*.cs sorted by path
//   regenerated on every dotnet build via Directory.Build.targets
//   DO NOT EDIT BY HAND
namespace DarkwoodMultiplayerFramework.Core;

public static class BuildIdentity
{{
    public const string Version = "{version}";
    public const string GitCommit = "{commit}";
    public const bool GitDirty = {"true" if dirty else "false"};
    public const string SourceFingerprint = "{src_fp}";
    public const string ProtocolVersion = "{proto}";
    public const string BuildUtc = "{utc}";
}}
"""
with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print(f"[dmf-build-identity] version={version} commit={commit[:12]} dirty={dirty} src={src_fp} protocol={proto} utc={utc} files={len(file_hashes)}")
